DjangoDGU/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import main
from lovely.views import first, second, third

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('lovely/', include('lovely.urls')),

]

lovely/urls.py
from django.urls import path
from .views import first, second, third

app_name = "lovely"
urlpatterns = [
    path('first/', first, name="first"),
    path('second/', second, name="second"),
    path('third/', third, name="third"),
]

lovely/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    view_count = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

lovely/views.py
from django.shortcuts import render

def first(request):
    return render(request, 'lovely/first.html')


def second(request):
    return render(request, 'lovely/second.html')


def third(request):
    return render(request, 'lovely/third.html')

posts/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'posts/main.html')

DjangoDGU/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/project.css' %}">

      
    <title>DjangoDGU</title>
  </head>
  <body>
      {% block content %}
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

lovely/templates/lovely/first.html
<body>
    <div class="tiledBackground">
        <h1>
    <pre>
    오늘은 그냥 평범한 날! 
    오늘하루도 힘차게 살아봐요! 
    </pre>
        </h1>
    </div>
</body>
<style>
    h1{
        font-size: 30pt; font: bold; color: blueviolet; font-family:'Mouse Memoirs', sans-serif; font-style: italic;
        color: blue;
    }
    body{
            background: url(https://img.huffingtonpost.com/asset/5d7089202500008d0004c18c.jpeg?ops=scalefit_630_noupscale) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    }

</style>

lovely/templates/lovely/second.html
<body>
<h1>
    <pre>
    오늘은 운세가 좋으시네요!! 
    복권을 사보거나 무언가를 시도해 보는 것은 어떨까요?
    </pre>
</h1>
</body>
<style>
    h1{
        font-size: 30pt; font: bold; color: blueviolet; font-family:'Mouse Memoirs', sans-serif; font-style: italic;
    }
    body{
                    background: url(https://media.istockphoto.com/vectors/five-little-pigs-with-chinese-gold-ingot-greetings-from-the-golden-vector-id1079146594) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    }


</style>

lovely/templates/lovely/third.html
<body>
<h1>
    <pre>
    "확실한 건, 부정적인 것보다 긍정적인 것이 낫다."
    "못할 것만 같은 일들도 시작하게 되면 하게 된다."
    "당신이 이루고자 하는 것에 시간만 투자한다면 분명 이룰수 있다고 본다.
                                          나는 분명히 그렇게 본다."
    "낙관주의는 성공으로 인도하는 믿음이다. 희망과 자신감이 없으면 아무것도 이루어질 수 없다."
    
    </pre>
    <div>
            <img src="https://i.pinimg.com/474x/88/de/d8/88ded8a13a6d4e992c3b8117616e6880.jpg" height=650 width=500>
        <img src="https://i.pinimg.com/474x/b7/e8/3a/b7e83a0ea5784d5fc5305b642fae9196--irish-blessing-irish-eyes.jpg" height=650>
    </div>

</h1>
</body>

<style>
    h1{
        font-size: 20pt; color: violet; font-family:'Mouse Memoirs', sans-serif; font-style: italic;
    }
    
    body{
        background-color: #D9E5FF;
    }
    
</style>

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block content %}
<body>
<h1>
    Have a good Day!
</h1>
<br>
<a href='{% url "lovely:third" %}'>오늘의 글귀</a>
    
<br><br><br><br><br><br>    
<h1>
    오늘의 운세는?
</h1>
<br>
<h2>
    느낌으로 버튼 4개중에 하나를 골라서 눌러주세요!! 
</h2>
<br><br><br> 

    <div class="menubtn">
    <button type="button" id="order" class="btn btn-outline-danger btn-lg" onclick="location.href='https://djangodgu-inugh.run.goorm.io/lovely/first/' ">1번</button>&nbsp; &nbsp; &nbsp; &nbsp;
    <br><br>
    <button type="button" id="flavor_of_the_month" class="btn btn-outline-success btn-lg" onclick="location.href='https://djangodgu-inugh.run.goorm.io/lovely/first/' ">2번</button>&nbsp; &nbsp; &nbsp;
    <br><br>
    <button type="button" id="recommendation" class="btn btn-outline-info btn-lg" onclick="location.href='https://djangodgu-inugh.run.goorm.io/lovely/first/' ">3번</button>
    <br><br>
    <button type="button" id="list" class="btn btn-outline-secondary btn-lg" onclick="location.href='https://djangodgu-inugh.run.goorm.io/lovely/second/' ">4번</button>
    </div>
</body>
<style>
    body{
        background: url(https://t1.daumcdn.net/cfile/tistory/2279C33C5818A6580B) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
        
    }
    a {
  background-color: red;
  color: white;
  padding: 1em 1.5em;
  text-decoration: none;
  text-transform: uppercase;
}
</style>
{% endblock %}